adminUser:
  password: vault:deathsummer/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:deathsummer/pipelineUser:token
  username: arcalos-bot
prow:
  hmacToken: vault:deathsummer/prow:hmacToken
segmentWriteKey: vault:deathsummer:segmentWriteKey
